#!/bin/bash

echo "Building image and attempting push..."

BUILD_COMMAND="docker build --rm -t easyjupyter/easyjupyter"
PUSH_COMMAND="docker push easyjupyter/easyjupyter:latest"
DOCKER_LOCATION=$EASY_JUPYTER_PATH/$DOCKER_FOLDER
eval $BUILD_COMMAND $DOCKER_LOCATION "&&" $PUSH_COMMAND
