#!/bin/bash

echo "Transferring local files to remote machine"
docker-machine ssh aws-sandbox mkdir -p $REMOTE_DATA_PATH
docker-machine scp -r $PWD aws-sandbox:$REMOTE_DATA_PATH

ej-write-state JUPYTER_ROOT "$REMOTE_DATA_PATH/${PWD##*/}"
