#!/bin/bash

echo "Stopping AWS machine"
docker-machine stop aws-sandbox

echo "Switching back to local work context"
ej-write-state AWS_ACTIVE false
# NOTE: Write blank state to run variables so that next run will trigger
# reset to local mode in current directory.
ej-write-state JUPYTER_ROOT
ej-write-state LOCAL_DATA_PATH
ej-write-state JUPYTER_CONFIG
