#!/bin/bash

echo "Transferring local files to remote machine"
export EASY_JUPYTER_BASE_HOME_PATH=/home/ubuntu/work
docker-machine ssh aws-sandbox mkdir -p $EASY_JUPYTER_BASE_HOME_PATH
docker-machine scp -r $PWD aws-sandbox:$EASY_JUPYTER_BASE_HOME_PATH
export EASY_JUPYTER_HOME_PATH=$EASY_JUPYTER_BASE_HOME_PATH/${PWD##*/}
