#!/bin/bash

echo "Transferring local files to remote machine"
EASY_JUPYTER_BASE_HOME_PATH=`cat $EASY_JUPYTER_PATH/vars/remote-base-path.dat`
docker-machine ssh aws-sandbox mkdir -p $EASY_JUPYTER_BASE_HOME_PATH
docker-machine scp -r $PWD aws-sandbox:$EASY_JUPYTER_BASE_HOME_PATH
echo "/home/ubuntu/work/${PWD##*/}" > $EASY_JUPYTER_PATH/vars/home-path.dat
