#!/bin/bash

EASY_JUPYTER_HOME_PATH=`cat $EASY_JUPYTER_PATH/vars/home-path.dat`
docker run --rm -p 8888:8888  \
	-v "$EASY_JUPYTER_HOME_PATH":/home/jovyan/work \
	-v $EASY_JUPYTER_PATH/jupyter_config:/home/jovyan/.jupyter \
	easyjupyter/easyjupyter start.sh jupyter notebook \
	--NotebookApp.token='' \
	--NotebookApp.notebook_dir='~/work' \
	--NotebookApp.ip='0.0.0.0' \
	--NotebookApp.allow_origin='https://colab.research.google.com' \
	--NotebookApp.port_retries=0
