#!/bin/bash

source $EASY_JUPYTER_PATH/vars/variables.sh
ej-read-state JUPYTER_ROOT

docker run --rm -p 8888:8888  \
	--name $JUPYTER_CONTAINER_NAME \
	-v $JUPYTER_ROOT:$CONTAINER_DATA_PATH \
	-v $EASY_JUPYTER_PATH/jupyter_config:/home/jovyan/.jupyter \
	-v /tmp:/tmp \
	--shm-size=2g \
	easyjupyter/easyjupyter start.sh jupyter notebook \
	--NotebookApp.token='' \
	--NotebookApp.notebook_dir='~/work' \
	--NotebookApp.ip='0.0.0.0' \
	--NotebookApp.allow_origin='https://colab.research.google.com' \
	--NotebookApp.port_retries=0
