#!/bin/bash

if ! docker-machine ls -q | grep --quiet '^aws-sandbox$' ; then
  docker-machine create --driver amazonec2 --amazonec2-open-port 8888 --amazonec2-region us-east-1 --amazonec2-instance-type t2.micro aws-sandbox
else
  docker-machine start aws-sandbox
  docker-machine regenerate-certs aws-sandbox --force
fi

echo "AWS Machine IP:"
echo $(docker-machine ip aws-sandbox)

echo "Using AWS Machine for Docker:"
eval $(docker-machine env aws-sandbox)

# Send local files to AWS
echo "Pushing local data to AWS"
easy-jupyter push-to-aws

echo "Opening local port 8888 and forwarding to remote machine"
docker-machine ssh aws-sandbox -f -N -L 8888:localhost:8888

echo "NOTE: you are now running docker on AWS. You should use 'easy-jupyer run-notebook/run-lab' to boot a jupyter process"
echo "NOTE: when finished, you must run: 'easy-jupyter stop-aws/destroy-aws' to turn off/delete the instance!"
echo "WARNING: data is only persisted remotely on the AWS instance. Run 'easy-jupyter pull-from-aws' to persist the data locally."
